databases:
  - name: atlas-db
    databaseName: atlas
    user: atlas_user
    plan: free
    region: frankfurt

services:
  - type: web
    name: atlas-backend
    env: docker
    plan: free
    region: frankfurt
    rootDir: backend
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:ZpH0r0X2UIXpOYW7PBUG82h0G4KxV4XnrbELmNkSchI=
      - key: APP_URL
        value: https://atlas-backend.onrender.com
      - key: FRONTEND_URL
        value: https://atlas-beryl-two.vercel.app
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: atlas-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: atlas-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: atlas-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: atlas-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: atlas-db
          property: password
